# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Upbit-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  target 'Upbit-CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Upbit-CloneUITests' do
    # Pods for testing
  end

end
